### ISSUE TITLE
[Feature Request] Support RTL (for google button specifically)

### ISSUE THREAD

**Issue by matanshukry** [dmjones/flutter_auth_buttons#30] opened 2020-05-20 21:14 UTC
I'm currently using the Facebook and the Google button.

While I can provider text for both, the alignment on the text with the icon is only correct for the Facebook one.

The google button will align the text to the end (left side in an rtl) and the icon to the right, creating a large margin between them. The text should also be aligned to the right, right after the icon.

**Comment by dmjones** [comment] 2020-07-10 13:55
Duplicate of #14, which I will look into addressing.

**Closed as completed by dmjones** 2020-07-10 13:55 UTC
Labels: duplicate
